CREATE
EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS public.location
(
    id BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID DEFAULT uuid_generate_v1(),
    city        VARCHAR(50) NOT NULL,
    airport     VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.flight
(
    id BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id           UUID DEFAULT uuid_generate_v1(),
    arrival_time        TIMESTAMP,
    departure_time      TIMESTAMP,
    price               NUMERIC    NOT NULL,
    arrival_location_id    BIGINT REFERENCES public.location(id),
    departure_location_id  BIGINT REFERENCES public.location(id),
    code                VARCHAR(50)  NOT NULL,
    status              VARCHAR(10)  NOT NULL DEFAULT 'SCHEDULED',
    active              BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.flighty_shedlock  (
                                         name VARCHAR(64),
                                         lock_until TIMESTAMP(3) NULL,
                                         locked_at TIMESTAMP(3) NULL,
                                         locked_by VARCHAR(255),
                                         PRIMARY KEY (name)
)