insert into location (city, airport) values ('Mahikeng', 'South Africa');
insert into location (city, airport) values ('Pittsburgh', 'United States');
insert into location (city, airport) values ('Sade', 'Nigeria');
insert into location (city, airport) values ('Zhongxin', 'China');
insert into location (city, airport) values ('Huntsville', 'United States');
insert into location (city, airport) values ('Jiaokou', 'China');
insert into location (city, airport) values ('Foshan', 'China');
insert into location (city, airport) values ('Tasböget', 'Kazakhstan');
insert into location (city, airport) values ('Povorino', 'Russia');
insert into location (city, airport) values ('Herong', 'China');
insert into location (city, airport) values ('Ar Rubū‘', 'Yemen');
insert into location (city, airport) values ('Estique', 'Peru');
insert into location (city, airport) values ('Oklahoma City', 'United States');
insert into location (city, airport) values ('Saint Louis', 'United States');
insert into location (city, airport) values ('Jungkat Selatan', 'Indonesia');
insert into location (city, airport) values ('Guxi', 'China');
insert into location (city, airport) values ('Čair', 'Macedonia');
insert into location (city, airport) values ('Idrinskoye', 'Russia');
insert into location (city, airport) values ('Kaabong', 'Uganda');
insert into location (city, airport) values ('Karanggeneng', 'Indonesia');
insert into location (city, airport) values ('Bogor', 'Indonesia');
insert into location (city, airport) values ('Bantarsari Kulon', 'Indonesia');
insert into location (city, airport) values ('Kuandian', 'China');
insert into location (city, airport) values ('Del Monte', 'Philippines');
insert into location (city, airport) values ('Datarkadu', 'Indonesia');
insert into location (city, airport) values ('Oliveirinha', 'Portugal');
insert into location (city, airport) values ('Nacka', 'Sweden');
insert into location (city, airport) values ('Nowe Warpno', 'Poland');
insert into location (city, airport) values ('Mahdia', 'Guyana');
insert into location (city, airport) values ('Biyan', 'Indonesia');
insert into location (city, airport) values ('Stockholm', 'Sweden');
insert into location (city, airport) values ('Fier', 'Albania');
insert into location (city, airport) values ('Nanmen', 'China');
insert into location (city, airport) values ('Kumla', 'Sweden');
insert into location (city, airport) values ('Ibirité', 'Brazil');
insert into location (city, airport) values ('Zwolle', 'Netherlands');
insert into location (city, airport) values ('Abut', 'Philippines');
insert into location (city, airport) values ('Shypyntsi', 'Ukraine');
insert into location (city, airport) values ('Châtillon', 'France');
insert into location (city, airport) values ('Keratéa', 'Greece');