server:
  port: ${SERVER_PORT:0}
  servlet:
    context-path: /ms-user

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  server:
    enableSelfPreservation: true

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/flighty}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:xiaominote9}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: /

jwt:
  expiry:
    default: ${JWT_DEFAULT_EXPIRY:3600000}
    remember: ${JWT_REMEMBERED_EXPIRY:10800000}
  secret: ${JWT_SECRET:temporarysecretkey}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer}

security:
  internal:
    header:
      name: ${INTERNAL_SECURITY_HEADER:X-Gateway-Token}
      value: ${INTERNAL_SECURITY_VALUE:token}

client:
  url:
    auth: ${AUTH_MS_URL:http://localhost:8081/auth-ms/}